micronaut:
  application:
    name: rangiffler-country-service
  server:
    port: 4001
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            your-provider:
              url: http://auth:9000/oauth2/jwks
    intercept-url-map:
      - pattern: /graphql
        access:
          - isAuthenticated()
      - pattern: /graphiql
        access:
          - isAnonymous()
      - pattern: /internal/country/*
        access:
          - isAnonymous()

datasources:
  default:
    url: 'jdbc:h2:mem:liquibaseDisabledDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'

graphql:
  enabled: true
  graphiql: # enables the /graphiql endpoint to test calls against your graph.
    enabled: true


liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog-master.yaml'

endpoints:
  liquibase:
    enabled: true
    sensitive: false
jpa:
    default:
        packages-to-scan:
            - 'com.leisan.country.service.model'
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: true

logger:
  levels:
    ROOT: INFO
    io.micronaut: INFO